# CPU
cpu_temp
cpu_text=R5 1600AF

# GPU
gpu_temp
gpu_text=GTX 1060

# Expensive stuff
# (ram_text and vram_text are custom values implemented w/ my own patch,
# 	will error out in terminal and show plain "RAM" and "VRAM on unpatched MangoHud builds)
ram
vram
swap
ram_text=16GB DDR4
vram_text=6GB GDDR5

# Music
media_player
media_player_format={title};{artist} / {album}

# General looks
round_corners=10
time
time_no_label
